const fs=require('fs');const D=require('./lessons.js');let DEEP={};try{DEEP=require('./deep.js')}catch(e){}
const {SEGMENTS,LESSONS,SKIPS,ORDER,GL}=D;
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#x27;');
const PLAY='<svg viewBox="0 0 16 16" fill="currentColor"><path d="M3 2v12l10-6z"/></svg>';
const pad=n=>String(n).padStart(2,'0');
const timerbar=home=>`<div class="timerbar" id="timer" aria-live="polite"><span class="t" id="tDisplay">25:00</span><span class="seg-now" id="tSeg">Class timer</span><button class="primary" id="tStart" type="button">Start</button><button id="tReset" type="button">Reset</button><button id="tBig" type="button" aria-pressed="false">Bigger text</button>${home?'':'<button id="tPresent" type="button" aria-pressed="false">Present</button><a class="home" href="index.html">All lessons</a>'}</div>`;
const sheet=()=>`<div class="sheet-back" id="sheetBack"></div><div class="sheet" id="sheet" role="dialog" aria-modal="true" aria-labelledby="sheetTitle"><div class="grip"></div><h4 id="sheetTitle"></h4><div id="sheetBody"></div><div class="actions"><a class="btn" id="sheetLink" href="#" target="_blank" rel="noopener">Open in Gospel Library</a><button class="btn quiet" type="button" id="sheetClose">Close</button></div></div>`;
const head=t=>`<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(t)}</title><link rel="stylesheet" href="assets/site.css"></head><body>`;
const foot=scr=>`<script>window.GF_SEGMENTS=${JSON.stringify(SEGMENTS.map(s=>[s[0],s[1],s[2]]))};window.GF_SCRIPTURES=${JSON.stringify(scr)};</script><script src="assets/site.js"></script></body></html>`;
const sources=()=>`<footer class="sources"><p>Built from two manuals:</p><p><a href="https://www.churchofjesuschrist.org/study/manual/gospel-foundations-digital-resource?lang=eng">Gospel Foundations: A Sunday School Class for New Members and Friends</a></p><p><a href="https://www.churchofjesuschrist.org/study/manual/preach-my-gospel-2023?lang=eng">Preach My Gospel (2023)</a></p></footer>`;
const poll=(q,opts)=>`<div class="poll"><p class="pq">${esc(q)}</p><div class="popts">${opts.map(o=>`<button class="popt" type="button">${esc(o)}</button>`).join('')}</div><div class="pres"></div></div>`;
const gallery=items=>`<div class="gallery">${items.map(i=>`<a href="${i[1]}" target="_blank" rel="noopener"><span class="ph">•</span><span class="cap">${esc(i[0])}</span></a>`).join('')}</div>`;
const IMG='referrerpolicy="no-referrer" onerror="this.closest(\'figure\').style.display=\'none\'"';
const photo=(src,caption)=>`<figure class="photo"><img src="${src}" alt="${esc(caption)}" loading="lazy" ${IMG}><figcaption>${esc(caption)}</figcaption></figure>`;
const photos=items=>items.length?`<div class="photo-row">${items.map(i=>photo(i[0],i[1])).join('')}</div>`:'';
const hero=h=>h?`<figure class="hero"><img src="${h[0]}" alt="${esc(h[1])}" ${IMG}><figcaption>${esc(h[1])}</figcaption></figure>`:'';
const clipsFor=(dp,seg)=>((dp.clips||[]).filter(c=>(c[3]||'why')===seg).map(c=>clip(c)).join(''))+((seg==='why'&&dp.clip)?clip(dp.clip):'');
const clip=c=>c?`<details class="clipbox"><summary>${PLAY}Watch a short clip: ${esc(c[0])}</summary><div class="video"><iframe src="https://www.youtube-nocookie.com/embed/${c[2]}" title="${esc(c[0])}" allow="encrypted-media; picture-in-picture" allowfullscreen loading="lazy"></iframe><a href="${c[1]}" target="_blank" rel="noopener">Open on YouTube</a></div></details>`:'';
const videos=vs=>'<div class="watch">'+vs.map(v=>v[2]?`<div class="video"><iframe src="https://www.youtube-nocookie.com/embed/${v[2]}" title="${esc(v[0])}" allow="encrypted-media; picture-in-picture" allowfullscreen loading="lazy"></iframe><a href="${v[1]}">${esc(v[0])}</a></div>`:`<a href="${v[1]}">${PLAY}${esc(v[0])}</a>`).join('')+'</div>';
const lessonTabs=(current)=>{let opts='<option value="index.html"'+(current===0?' selected':'')+'>Class overview</option>';for(let i=1;i<=12;i++){const L=LESSONS.find(x=>x.n===i);const label=L?`Lesson ${i} \u2014 ${L.date}`:`Lesson ${i}`;opts+=`<option value="lesson-${pad(i)}.html"${i===current?' selected':''}>${esc(label)}</option>`}return `<div class="lessonjump home-only"><label for="jumpLesson">Jump to</label><select id="jumpLesson">${opts}</select></div>`};
function lesson(L,prev,nxt){const n=L.n,scr={};let h=head(`Lesson ${n}: ${L.title}`)+timerbar(false)+lessonTabs(n)+'<main>';
h+=`<p class="term">Lesson ${n} of 12, ${esc(L.date)}</p><h1>${esc(L.title)}</h1><p class="anchors">From ${esc(L.anchors)}</p>`;
const dp0=DEEP[n]||{};h+=hero(dp0.hero);
let fu="Did you read Joseph Smith History 1:5 to 20? What did you notice about what he was asking?";if(prev)fu=`Last week we were invited: ${esc(prev.invite)} What happened?`;
const dp=DEEP[n]||{};if(dp.scr)h+='<p class="home-only">Anything with a plus sign opens for more: the full verse text, the history behind it, and what a Catholic or Protestant friend would actually say back.</p>';
h+=`<section class="lesson-seg"><h2>Follow up</h2><div class="prompt">${fu}</div>${dp.follow||''}</section>`;
h+=`<section class="lesson-seg"><h2>The unanswered question</h2><p class="question">${esc(L.q)}</p>${dp.question||''}${clipsFor(dp,'question')}<p class="hold">Hold the question. The scriptures answer it next.</p></section>`;
h+='<section class="lesson-seg"><h2>Scriptures</h2><p>Read in class. Someone reads it aloud; then we ask what it means for someone sitting here.</p><ul class="reads">';
L.read.forEach((r,i)=>{const dd=(dp.scr||{})[r.d]||{};if(r.t||dd.v){const k=`r${n}_${i}`;scr[k]={t:r.d,u:r.u,v:r.t||dd.v,c:dd.c||''};h+=`<li><span class="r">${esc(r.d)}</span><button class="open" type="button" data-sheet="${k}">Read</button></li>`}else h+=`<li><span class="r">${esc(r.d)}</span><a class="open" href="${r.u}" target="_blank" rel="noopener">Read</a></li>`});
h+='</ul>'+(dp.photos1?photos(dp.photos1):'')+(dp.scriptures||'')+clipsFor(dp,'scriptures')+'<div class="home-only"><h3>Sent to you this week</h3>';
if(dp.scr){h+='<p>Open any of these for the text and a note on why it is on the list.</p><ul class="sendlist2">'+L.send.map((r,i)=>{const dd=dp.scr[r.d];if(dd&&dd.v){const k=`s${n}_${i}`;scr[k]={t:r.d,u:r.u,v:dd.v,c:dd.c||''};return `<li><button class="ref" type="button" data-sheet="${k}">${esc(r.d)}</button>${dd.c?`<span class="c">${dd.c.split('. ')[0]}.</span>`:''}</li>`}return `<li><a href="${r.u}">${esc(r.d)}</a></li>`}).join('')+'</ul>'}else{h+='<p class="sendlist">'+L.send.map(r=>`<a href="${r.u}">${esc(r.d)}</a>`).join(' · ')+'</p>'}
h+='</div></section>';
h+=`<section class="lesson-seg"><h2>What we believe</h2><p class="lab">The answer to today's question</p><p class="question small">${esc(L.q)}</p><button class="reveal" type="button" aria-controls="answer" aria-expanded="false">Show the answer</button><div class="answer" id="answer"><p>${esc(L.a)}</p></div><ul class="plain">`+L.believe.map(b=>`<li>${esc(b)}</li>`).join('')+'</ul>'+(dp.believe||'')+'</section>';
const askBlock=dp.poll?poll(L.ask,dp.poll):`<div class="prompt">Talk about this: ${esc(L.ask)}</div>`;
h+=`<section class="lesson-seg"><h2>Why it matters</h2><p>${esc(L.dive)}</p>${clipsFor(dp,'why')}${askBlock}<div class="whyline">${esc(L.why)}</div>${dp.gallery?'<div class="home-only">'+gallery(dp.gallery)+'</div>':''}${dp.why||''}</section>`;
const c=L.cmp;h+=`<section class="lesson-seg"><h2>Across the Christian world</h2><p>Each column is that tradition's own answer, from its own sources.</p><div class="compare"><div class="col"><h4>Catholic</h4><p>${esc(c.c)}</p><p class="src">${esc(c.cs)}</p></div><div class="col"><h4>Protestant</h4><p>${esc(c.p)}</p><p class="src">${esc(c.ps)}</p></div><div class="col restored"><h4>Restored</h4><p>${esc(c.r)}</p><p class="src">${esc(c.rs)}</p></div></div><p class="gap"><b>What the Restoration adds:</b> ${esc(c.gap)}</p>${dp.compare||''}</section>`;
const inv=L.invite_url?`<p><a class="btn" href="${L.invite_url}" target="_blank" rel="noopener">Open it</a></p>`:'';
h+=`<section class="lesson-seg"><h2>Testify, invite, share it</h2>${dp.testify||''}${clipsFor(dp,'testify')}${dp.photos2?photos(dp.photos2):''}<div class="invite"><h3>${esc(L.invite)}</h3>${inv}<p class="promise">The promise: ${esc(L.promise)}</p></div><div class="share"><p class="lab">If a friend asked, you could say:</p><p class="say">“${esc(L.share)}”</p></div></section>`;
const clips=(dp.study||[]).filter(v=>v[2]),talks=L.videos.concat((dp.study||[]).filter(v=>!v[2]));
h+='<section class="home-only"><h2>Watch and study this week</h2>'+(clips.length?'<h3>Short clips, two to four minutes</h3>'+videos(clips):'')+'<h3>Full talks and reading</h3>'+videos(talks)+'</section>';
const QZ=L.quiz.concat(dp.quiz||[]);h+=`<section class="home-only"><h2>${QZ.length>3?'Five':'Three'} quick questions</h2><div class="quiz">`+QZ.map(q=>`<div class="qq" data-answer="${q[2]}" data-note="${esc(q[3])}"><p class="prompt-q">${esc(q[0])}</p><div class="opts">${q[1].map(o=>`<button class="opt" type="button">${esc(o)}</button>`).join('')}</div><p class="fb"></p></div>`).join('')+'<p class="score" id="score"></p></div></section>';
const pv=prev?`<a href="lesson-${pad(prev.n)}.html">Previous: Lesson ${prev.n}</a>`:'<a href="index.html">Class overview</a>';const nx=nxt?`<a href="lesson-${pad(nxt.n)}.html">Next: Lesson ${nxt.n}</a>`:'<a href="index.html">Back to the overview</a>';
h+=`<nav class="nav home-only">${pv}${nx}</nav>`+sources()+'</main>'+'<div class="pnav" id="pnav"><button type="button" id="pPrev">\u2039 Back</button><span class="pmid"><b id="pName"></b><span id="pStep"></span><span id="pTimer"></span></span><button type="button" id="pNext">Next \u203a</button></div>'+sheet()+foot(scr);return h}
function index(){const scr={
dc11:{t:"Doctrine and Covenants 11:21",u:GL+"dc-testament/dc/11?lang=eng&id=p21#p21",v:"<sup>21</sup>Seek not to declare my word, but first seek to obtain my word, and then shall your tongue be loosed; then, if you desire, you shall have my Spirit and my word, yea, the power of God unto the convincing of men."},
john17:{t:"John 17:3",u:GL+"nt/john/17?lang=eng&id=p3#p3",v:"<sup>3</sup>And this is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent."},
dc131:{t:"Doctrine and Covenants 131:6",u:GL+"dc-testament/dc/131?lang=eng&id=p6#p6",v:"<sup>6</sup>It is impossible for a man to be saved in ignorance."},
alma31:{t:"Alma 31:5",u:GL+"bofm/alma/31?lang=eng&id=p5#p5",v:"<sup>5</sup>And now, as the preaching of the word had a great tendency to lead the people to do that which was just—yea, it had had more powerful effect upon the minds of the people than the sword, or anything else, which had happened unto them—therefore Alma thought it was expedient that they should try the virtue of the word of God."},
dc88:{t:"Doctrine and Covenants 88:78–80",u:GL+"dc-testament/dc/88?lang=eng&id=p78-p80#p78",v:"<sup>78</sup>Teach ye diligently and my grace shall attend you, that you may be instructed more perfectly in theory, in principle, in doctrine, in the law of the gospel, in all things that pertain unto the kingdom of God, that are expedient for you to understand; … <sup>80</sup>That ye may be prepared in all things when I shall send you again to magnify the calling whereunto I have called you, and the mission with which I have commissioned you."},
"2ne25":{t:"2 Nephi 25:26",u:GL+"bofm/2-ne/25?lang=eng&id=p26#p26",v:"<sup>26</sup>And we talk of Christ, we rejoice in Christ, we preach of Christ, we prophesy of Christ, and we write according to our prophecies, that our children may know to what source they may look for a remission of their sins."},
"1pet":{t:"1 Peter 3:15",u:GL+"nt/1-pet/3?lang=eng&id=p15#p15",v:"<sup>15</sup>But sanctify the Lord God in your hearts: and be ready always to give an answer to every man that asketh you a reason of the hope that is in you with meekness and fear:"},
dc18:{t:"Doctrine and Covenants 18:15–16",u:GL+"dc-testament/dc/18?lang=eng&id=p15-p16#p15",v:"<sup>15</sup>And if it so be that you should labor all your days in crying repentance unto this people, and bring, save it be one soul unto me, how great shall be your joy with him in the kingdom of my Father! <sup>16</sup>And now, if your joy will be great with one soul that you have brought unto me into the kingdom of my Father, how great will be your joy if you should bring many souls unto me!"},
alma17:{t:"Alma 17:2–3",u:GL+"bofm/alma/17?lang=eng&id=p2-p3#p2",v:"<sup>2</sup>…they had waxed strong in the knowledge of the truth; for they were men of a sound understanding and they had searched the scriptures diligently, that they might know the word of God. <sup>3</sup>But this is not all; they had given themselves to much prayer, and fasting; therefore they had the spirit of prophecy, and the spirit of revelation, and when they taught, they taught with power and authority of God."},
jsh:{t:"Joseph Smith History 1:10, 16–17",u:GL+"pgp/js-h/1?lang=eng&id=p5-p20#p5",v:"<sup>10</sup>In the midst of this war of words and tumult of opinions, I often said to myself: What is to be done? Who of all these parties are right; or, are they all wrong together? If any one of them be right, which is it, and how shall I know it? <sup>16</sup>…I saw a pillar of light exactly over my head, above the brightness of the sun, which descended gradually until it fell upon me. <sup>17</sup>…When the light rested upon me I saw two Personages, whose brightness and glory defy all description, standing above me in the air. One of them spake unto me, calling me by name and said, pointing to the other: This is My Beloved Son. Hear Him!"}};
let h=head('Gospel Foundations, Fall 2026')+timerbar(true)+lessonTabs(0)+'<main>';
h+=`<header><p class="term">Sunday School, second hour, Fall 2026</p><h1>Gospel Foundations</h1><p class="thesis">You are a child of God. You came here to receive a body, to be tested, and to become like Jesus Christ. This class is about the restored gospel that makes that possible, and about knowing it well enough to explain it to someone else.</p><p class="who">Taught by Richard LeDuc and Brandon Huston. Twelve Sundays, 25 minutes each.</p><div class="prompt">Talk about this: if a friend asked you what our church believes, how many sentences could you give them before you ran out?</div></header>${poll("Show of hands: how far could you get?",["A sentence or two, then I'd stall","Three to five sentences","I could go a long while"])}<hr class="gold-rule">`;
h+=`<section><h2>Learn it. Understand why it matters. Share it.</h2><p>Every principle we study this fall goes through those three steps. It is the order Preach My Gospel gives a missionary: obtain the word before you declare it, teach so people understand and can see the blessing, then testify and invite. Open any scripture to read it.</p><div class="thread">`;
h+=`<div class="step"><h3>Learn what we believe</h3><p class="pmg">Preach My Gospel, chapter 10: "Seek to obtain my word"</p><blockquote>"It is the first principle of the gospel to know for a certainty the character of God, and to know that we may converse with Him as one man converses with another."<span class="by">Joseph Smith, King Follett discourse, April 1844</span></blockquote><blockquote>"A man is saved no faster than he gets knowledge."<span class="by">Joseph Smith, Teachings of Presidents of the Church: Joseph Smith, chapter 22</span></blockquote><p class="refs">Read: <button class="ref" data-sheet="dc11">D&amp;C 11:21</button> · <button class="ref" data-sheet="john17">John 17:3</button> · <button class="ref" data-sheet="dc131">D&amp;C 131:6</button></p>${videos([["Jeffrey R. Holland, Safety for the Soul (Oct 2009)","https://www.churchofjesuschrist.org/study/general-conference/2009/10/safety-for-the-soul?lang=eng"]])}</div>`;
h+=`<div class="step"><h3>Understand why it matters</h3><p class="pmg">Preach My Gospel, chapters 10 and 11: teach for understanding, promise blessings</p><blockquote>"True doctrine, understood, changes attitudes and behavior. The study of the doctrines of the gospel will improve behavior quicker than a study of behavior will improve behavior."<span class="by">Boyd K. Packer, "Little Children," October 1986</span></blockquote><blockquote>"The fundamental principles of our religion are the testimony of the Apostles and Prophets, concerning Jesus Christ, that He died, was buried, and rose again the third day, and ascended into heaven; and all other things which pertain to our religion are only appendages to it."<span class="by">Joseph Smith, Teachings: Joseph Smith, chapter 3</span></blockquote><p class="refs">Read: <button class="ref" data-sheet="alma31">Alma 31:5</button> · <button class="ref" data-sheet="dc88">D&amp;C 88:78–80</button> · <button class="ref" data-sheet="2ne25">2 Nephi 25:26</button></p>${videos([["Boyd K. Packer, Little Children (Oct 1986)","https://www.churchofjesuschrist.org/study/general-conference/1986/10/little-children?lang=eng"],["D. Todd Christofferson, The Doctrine of Christ (Apr 2012)","https://www.churchofjesuschrist.org/study/general-conference/2012/04/the-doctrine-of-christ?lang=eng"],["Russell M. Nelson, Hear Him (Apr 2020)","https://www.churchofjesuschrist.org/study/general-conference/2020/04/36nelson?lang=eng"]])}</div>`;
h+=`<div class="step"><h3>Share it</h3><p class="pmg">Preach My Gospel, chapter 11: testify, invite, promise blessings</p><blockquote>"The Standard of Truth has been erected; no unhallowed hand can stop the work from progressing; persecutions may rage, mobs may combine, armies may assemble, calumny may defame, but the truth of God will go forth boldly, nobly, and independent, till it has penetrated every continent, visited every clime, swept every country, and sounded in every ear."<span class="by">Joseph Smith, the Wentworth Letter, March 1842</span></blockquote><p class="refs">Read: <button class="ref" data-sheet="1pet">1 Peter 3:15</button> · <button class="ref" data-sheet="dc18">D&amp;C 18:15–16</button> · <button class="ref" data-sheet="alma17">Alma 17:2–3</button></p>${videos([["Dieter F. Uchtdorf, Missionary Work: Sharing What Is in Your Heart (Apr 2019)","https://www.churchofjesuschrist.org/study/general-conference/2019/04/36uchtdorf?lang=eng"],["Dallin H. Oaks, Sharing the Restored Gospel (Oct 2016)","https://www.churchofjesuschrist.org/study/general-conference/2016/10/sharing-the-restored-gospel?lang=eng"]])}</div></div></section>`;
h+=`<section><h2>How every Sunday works</h2><p>Same shape every week, so you always know where we are. If you have watched missionaries teach, you will recognize it. Open a segment to see what happens in it.</p><div class="prompt">The timer at the top runs the whole class. The segment we are in lights up as we go.</div><div class="clock">`;
for(const s of SEGMENTS)h+=`<button class="seg" data-min="${s[1]}" data-start="${s[0]}" aria-expanded="false"><span class="seg-head"><span class="mins">${s[0]}–${s[0]+s[1]}</span><span class="name">${esc(s[2])}</span><span class="chev">›</span></span></button><div class="seg-body"><p>${esc(s[3])}</p></div>`;
h+='</div><p class="clock-note">Segment height matches its minutes.</p><p class="frame-note">This seven-part shape is our own way of teaching both manuals together each week. You will not find it printed in either book; it is how your teachers chose to pace the material, not a structure either manual specifies.</p></section>';
const c=LESSONS[0].cmp;h+=`<section><h2>Across the Christian world</h2><p>Here is what that segment looks like, using the question we open with next week: where does authority to act for God come from? Each column is that tradition's own answer.</p><div class="compare"><div class="col"><h4>Catholic</h4><p>${esc(c.c)}</p><p class="src">${esc(c.cs)}</p></div><div class="col"><h4>Protestant</h4><p>${esc(c.p)}</p><p class="src">${esc(c.ps)}</p></div><div class="col restored"><h4>Restored</h4><p>${esc(c.r)}</p><p class="src">${esc(c.rs)}</p></div></div><p style="margin-top:10px">We won't knock anyone's faith. We will learn what our friends believe accurately enough to say it back to them, then say plainly what the Restoration adds.</p></section>`;
h+=`<section><h2>The twelve Sundays</h2><p>Open a lesson to see its page. Each week's page goes out the week before.</p><ul class="sundays"><li><a class="row" href="index.html"><span class="date">Sep 6</span><span class="title">Today: what this class is<span class="sub">The purpose, the pattern, the twelve Sundays, and your first invitation.</span></span></a></li>`;
const by={};LESSONS.forEach(L=>by[L.date]=L);
for(const d of ORDER.slice(1)){if(SKIPS[d])h+=`<li class="skip"><span class="date">${d}</span><span>${esc(SKIPS[d])}</span></li>`;else{const L=by[d];h+=`<li><a class="row" href="lesson-${pad(L.n)}.html"><span class="date">${d}</span><span class="title"><span class="n">${L.n}</span>${esc(L.title)}<span class="sub">${esc(L.q)}</span></span></a></li>`}}
h+='</ul></section>';
h+=`<section><h2>This week</h2><div class="invite"><h3>Will you read Joseph Smith History 1:5–20 before next Sunday?</h3><p>Notice what a fourteen-year-old was actually asking, and what he was told. Lesson 1 opens with it.</p><p>Read <button class="ref" data-sheet="jsh">Joseph Smith History 1:5–20</button></p><p class="promise">The promise he acted on: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him." (James 1:5)</p></div><h3 style="margin-top:28px">Three quick questions</h3><p>Try these after you read. Each week's page ends the same way.</p><div class="quiz"><div class="qq" data-answer="1" data-note="Fourteen. He says so in verse 7."><p class="prompt-q">How old was Joseph Smith when he went into the grove?</p><div class="opts"><button class="opt" type="button">Twelve</button><button class="opt" type="button">Fourteen</button><button class="opt" type="button">Seventeen</button></div><p class="fb"></p></div><div class="qq" data-answer="2" data-note="James 1:5. He said no passage ever struck his heart with more power (verse 12)."><p class="prompt-q">Which verse sent him there?</p><div class="opts"><button class="opt" type="button">Matthew 7:7</button><button class="opt" type="button">Proverbs 3:5</button><button class="opt" type="button">James 1:5</button></div><p class="fb"></p></div><div class="qq" data-answer="0" data-note="Join none of them (verse 19). That answer is why a restoration was needed, not a reform."><p class="prompt-q">What was he told about the churches?</p><div class="opts"><button class="opt" type="button">Join none of them</button><button class="opt" type="button">Join the Methodists</button><button class="opt" type="button">Start his own</button></div><p class="fb"></p></div><p class="score" id="score"></p></div></section>`;
return h+sources()+'</main>'+sheet()+foot(scr)}
fs.mkdirSync('public/assets',{recursive:true});fs.copyFileSync('assets/site.css','public/assets/site.css');fs.copyFileSync('assets/site.js','public/assets/site.js');
fs.writeFileSync('public/index.html',index());
LESSONS.forEach((L,i)=>fs.writeFileSync(`public/lesson-${pad(L.n)}.html`,lesson(L,LESSONS[i-1],LESSONS[i+1])));
console.log('built',LESSONS.length+1,'pages');
