const GL="https://www.churchofjesuschrist.org/study/scriptures/";
function ref(d,path,ids,text){let u=GL+path+"?lang=eng";if(ids)u+="&id="+ids+"#"+ids.split("-")[0].split(",")[0];return {d,u,t:text||null}}
const SEGMENTS=[
 [0,2,"Follow up","Who did last week's invitation? What did you find?"],
 [2,2,"The unanswered question","A question much of the Christian world struggles to answer, and the restored gospel answers."],
 [4,6,"Scriptures","Two or three passages, read aloud by someone in the room. We find the doctrine in the text before anyone states it."],
 [10,4,"What we believe","The principle we just found, stated plainly. Terms defined."],
 [14,4,"Why it matters","A short clip or story, one discussion question, and one sentence on how this changes your life."],
 [18,4,"Across the Christian world","What Catholics and Protestants believe about the same principle, in their own words, next to ours."],
 [22,3,"Testify, invite, share it","A testimony, one invitation with its promised blessing, and the sentence you could say to a friend."],
];
const LESSONS=[
{n:1,date:"Sep 13",title:"Why a Restoration, and who holds the authority?",
 anchors:"Preach My Gospel, Lesson 1; Gospel Foundations, The Restored Church of Jesus Christ Today",
 q:"Why are there so many churches, and if Christ built one, where did it go?",
 a:"Christ built one Church with apostles holding His authority. After they died, the authority was withdrawn and the Church He organized was gone from the earth. Reformers could correct doctrine, but no one can reclaim authority that God has taken back; it has to be given again. In 1829 it was, by the same men who held it anciently.",
 believe:["Christ established a Church with apostles holding priesthood authority.","After the apostles died there was a widespread falling away, and the authority was withdrawn.","Reformers sought light but could not restore what was lost. Authority must be given, not reclaimed.","God restored the gospel through Joseph Smith; heavenly messengers restored the priesthood and its keys.","Living prophets and apostles lead the Church today in an unbroken line from those ordinations."],
 read:[ref("Amos 8:11–12","ot/amos/8","p11-p12","<sup>11</sup>Behold, the days come, saith the Lord God, that I will send a famine in the land, not a famine of bread, nor a thirst for water, but of hearing the words of the Lord: <sup>12</sup>And they shall wander from sea to sea, and from the north even to the east, they shall run to and fro to seek the word of the Lord, and shall not find it."),
   ref("2 Thessalonians 2:1–3","nt/2-thes/2","p1-p3","<sup>1</sup>Now we beseech you, brethren, by the coming of our Lord Jesus Christ, and by our gathering together unto him, <sup>2</sup>That ye be not soon shaken in mind, or be troubled, neither by spirit, nor by word, nor by letter as from us, as that the day of Christ is at hand. <sup>3</sup>Let no man deceive you by any means: for that day shall not come, except there come a falling away first, and that man of sin be revealed, the son of perdition;"),
   ref("Joseph Smith History 1:16–19","pgp/js-h/1","p16-p19","<sup>16</sup>…I saw a pillar of light exactly over my head, above the brightness of the sun, which descended gradually until it fell upon me. <sup>17</sup>…When the light rested upon me I saw two Personages, whose brightness and glory defy all description, standing above me in the air. One of them spake unto me, calling me by name and said, pointing to the other: This is My Beloved Son. Hear Him! <sup>18</sup>My object in going to inquire of the Lord was to know which of all the sects was right, that I might know which to join. No sooner, therefore, did I get possession of myself, so as to be able to speak, than I asked the Personages who stood above me in the light, which of all the sects was right (for at this time it had never entered into my heart that all were wrong), and which I should join. <sup>19</sup>I was answered that I must join none of them, for they were all wrong; and the Personage who addressed me said that all their creeds were an abomination in his sight; that those professors were all corrupt; that: “they draw near to me with their lips, but their hearts are far from me, they teach for doctrines the commandments of men, having a form of godliness, but they deny the power thereof.”")],
 send:[ref("Acts 3:19–21","nt/acts/3","p19-p21"),ref("Matthew 16:18–19","nt/matt/16","p18-p19"),ref("1 Peter 2:9","nt/1-pet/2","p9"),ref("Ephesians 2:19–20","nt/eph/2","p19-p20"),ref("Ephesians 4:11–14","nt/eph/4","p11-p14"),ref("Hebrews 5:4","nt/heb/5","p4"),ref("2 Nephi 28","bofm/2-ne/28"),ref("Galatians 1:6–9","nt/gal/1","p6-p9"),ref("D&C 13","dc-testament/dc/13"),ref("D&C 27:12–13","dc-testament/dc/27","p12-p13"),ref("D&C 110:11–16","dc-testament/dc/110","p11-p16"),ref("Joseph Smith History 1:68–72","pgp/js-h/1","p68-p72"),ref("Articles of Faith 1:5–6","pgp/a-of-f/1","p5-p6")],
 dive:"Preach My Gospel puts it plainly: after Rome adopted Christianity, important religious questions were settled by debate in councils rather than by revelation. Those councils (Nicaea in 325, Constantinople in 381) produced the creeds. Joseph Smith History 1:19 is the Lord's verdict on them.",
 ask:"What is the difference between reforming something and restoring it?",
 why:"Authority is what turns an ordinance into a covenant; without it, the same words are only a ceremony.",
 cmp:{c:"Christ gave Peter the keys; every bishop since stands in an unbroken line of ordination from him, so the Church has never lost its authority.",cs:"Matthew 16:18–19; Catechism 861–862",
  p:"Scripture is the final authority and every believer is a priest. Authority comes from properly believing in Jesus, not from anyone laying hands on your head. That is one of the least understood differences between Latter-day Saint theology and the rest of Christianity: most Protestants reject lineal, hands-on-head, passed-down authority entirely.",ps:"1 Peter 2:9; the Reformation, 1517 onward",
  r:"Authority was lost after the apostles died and given back by heavenly messengers: John the Baptist in 1829, then Peter, James, and John.",rs:"Hebrews 5:4; D&C 13; 27:12–13",
  gap:"Neither tradition can point to when and by whom authority was conferred on them by God. We can, with names, dates, and places."},
 invite:"Will you read the 2020 proclamation on the Restoration and mark the one line you would use with a friend?",
 invite_url:"https://www.churchofjesuschrist.org/study/scriptures/the-restoration-of-the-fulness-of-the-gospel-of-jesus-christ/a-bicentennial-proclamation-to-the-world?lang=eng",
 promise:"Living prophets are our greatest safety (Preach My Gospel, Lesson 1).",
 share:"Our church can tell you exactly when God gave it authority, and by whom.",
 videos:[["Tad R. Callister, What Is the Blueprint of Christ's Church? (CES devotional, 2014)","https://www.churchofjesuschrist.org/study/broadcasts/worldwide-devotional-for-young-adults/2014/01/what-is-the-blueprint-of-christs-church?lang=eng"],
  ["Jeffrey R. Holland, Prophets in the Land Again (Oct 2006)","https://www.churchofjesuschrist.org/study/general-conference/2006/10/prophets-in-the-land-again?lang=eng"],
  ["Gospel Topics: Restoration of the Priesthood","https://www.churchofjesuschrist.org/study/manual/gospel-topics/restoration-of-the-priesthood?lang=eng"]],
 quiz:[["Who restored the Aaronic Priesthood in 1829?",["John the Baptist","Peter, James, and John","Moroni"],0,"John the Baptist (D&C 13; JS History 1:68–72)."],
  ["Which prophet foretold a famine of hearing the words of the Lord?",["Isaiah","Amos","Malachi"],1,"Amos 8:11–12."],
  ["Who conferred the Melchizedek Priesthood on Joseph Smith and Oliver Cowdery?",["Moroni","Elijah","Peter, James, and John"],2,"Peter, James, and John (D&C 27:12–13)."]]},

{n:2,date:"Sep 27",title:"Who God is, and who you are",
 anchors:"Preach My Gospel, Lesson 1; Gospel Foundations, Praying to Our Heavenly Father",
 q:"If God is a spirit \"without body, parts, or passions,\" how am I made in His image?",
 a:"You are made in His image because He has one. The Father and the Son each have a glorified body of flesh and bones; the Holy Ghost is a personage of spirit. They are three beings, perfectly one in purpose. Joseph Smith saw two of them standing in the air.",
 believe:["God is our literal Father; we are His spirit children, created in His image.","He has a glorified body of flesh and bones (D&C 130:22). The Son does too. The Holy Ghost is a personage of spirit.","The Father, the Son, and the Holy Ghost are three distinct beings, perfectly one in purpose.","Because we are His children, we can become like Him. That is the whole point of the plan."],
 read:[ref("Acts 17:28–29","nt/acts/17","p28-p29","<sup>28</sup>For in him we live, and move, and have our being; as certain also of your own poets have said, For we are also his offspring. <sup>29</sup>Forasmuch then as we are the offspring of God, we ought not to think that the Godhead is like unto gold, or silver, or stone, graven by art and man's device."),
   ref("Acts 7:55–56","nt/acts/7","p55-p56","<sup>55</sup>But he, being full of the Holy Ghost, looked up stedfastly into heaven, and saw the glory of God, and Jesus standing on the right hand of God, <sup>56</sup>And said, Behold, I see the heavens opened, and the Son of man standing on the right hand of God."),
   ref("John 17:3, 20–23","nt/john/17","p3,p20-p23","<sup>3</sup>And this is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent. <sup>21</sup>That they all may be one; as thou, Father, art in me, and I in thee, that they also may be one in us: that the world may believe that thou hast sent me.")],
 send:[ref("Genesis 1:26–27","ot/gen/1","p26-p27"),ref("Matthew 3:16–17","nt/matt/3","p16-p17"),ref("Romans 8:16–17","nt/rom/8","p16-p17"),ref("Hebrews 12:9","nt/heb/12","p9"),ref("D&C 93:29","dc-testament/dc/93","p29"),ref("D&C 130:22–23","dc-testament/dc/130","p22-p23"),ref("Moses 1:39","pgp/moses/1","p39"),ref("Abraham 3:22–25","pgp/abr/3","p22-p25"),ref("Joseph Smith History 1:17","pgp/js-h/1","p17")],
 dive:"The First Vision settled in one moment what centuries of councils had argued about: two Personages, one pointing to the other. Everything Joseph learned that morning about God was learned by seeing Him.",
 ask:"If God has a body, what does that tell you about why you needed one?",
 why:"You can only become like a God you can actually resemble.",
 cmp:{c:"One God in three persons of one substance, as defined at Nicaea and Constantinople. God is pure spirit, without a body.",cs:"Nicene Creed; Catechism 202, 370",
  p:"The same Trinity. God is \"without body, parts, or passions.\"",ps:"Thirty-Nine Articles, Article I; Westminster Confession 2.1",
  r:"Three separate beings, one in purpose. The Father and the Son have bodies of flesh and bones as tangible as ours.",rs:"D&C 130:22; Acts 7:55–56; JS History 1:17",
  gap:"A God without a body is a God we cannot resemble. A literal Father with a literal body is what makes \"become like Him\" mean something."},
 invite:"Will you pray this week addressing God as your Father and tell Him one thing you want to become?",invite_url:null,
 promise:"\"Those that seek me early shall find me\" (Proverbs 8:17).",
 share:"We believe God is your literal Father, with a body, and that is why you have one.",
 videos:[["Jeffrey R. Holland, The Only True God and Jesus Christ Whom He Hath Sent (Oct 2007)","https://www.churchofjesuschrist.org/study/general-conference/2007/10/the-only-true-god-and-jesus-christ-whom-he-hath-sent?lang=eng"],
  ["Jeffrey R. Holland, The Grandeur of God (Oct 2003)","https://www.churchofjesuschrist.org/study/general-conference/2003/10/the-grandeur-of-god?lang=eng"],
  ["Gospel Topics: Godhead","https://www.churchofjesuschrist.org/study/manual/gospel-topics/godhead?lang=eng"]],
 quiz:[["According to D&C 130:22, which members of the Godhead have bodies of flesh and bones?",["The Father only","The Father and the Son","All three"],1,"The Father and the Son; the Holy Ghost is a personage of spirit (D&C 130:22)."],
  ["What did Stephen see in Acts 7?",["A pillar of fire","Jesus standing on the right hand of God","An angel with a book"],1,"Jesus standing on the right hand of God (Acts 7:55–56)."],
  ["Which creed describes God as without body, parts, or passions?",["The Apostles' Creed","The Thirty-Nine Articles","The Nicene Creed"],1,"The Thirty-Nine Articles, Article I (also Westminster Confession 2.1)."]]},

{n:3,date:"Oct 11",title:"The plan, part 1: before birth, the Fall, and why you have a body",
 anchors:"Preach My Gospel, Lesson 2; Gospel Foundations, Your Body Is Sacred",
 q:"Where was I before I was born, and is my body a gift or a problem?",
 a:"You lived with God before you were born, and you chose to come. The earth was made so you could get a body and be tested. The Fall was the doorway into that, not a catastrophe; Adam and Eve rejoiced in it. Your body is part of becoming like a God who has one.",
 believe:["We lived with God before birth. He knew us, and we chose His plan.","The earth was created so we could gain bodies and be tested.","The Fall was not a disaster; it was the doorway. Adam and Eve rejoiced in it.","We are accountable for our own sins, not Adam's (Articles of Faith 1:2).","The body is sacred. It is part of becoming like a God who has one."],
 read:[ref("Job 38:4–7","ot/job/38","p4-p7","<sup>4</sup>Where wast thou when I laid the foundations of the earth? declare, if thou hast understanding. <sup>5</sup>Who hath laid the measures thereof, if thou knowest? or who hath stretched the line upon it? <sup>6</sup>Whereupon are the foundations thereof fastened? or who laid the corner stone thereof; <sup>7</sup>When the morning stars sang together, and all the sons of God shouted for joy?"),
   ref("2 Nephi 2:22–25","bofm/2-ne/2","p22-p25","<sup>22</sup>And now, behold, if Adam had not transgressed he would not have fallen, but he would have remained in the garden of Eden. And all things which were created must have remained in the same state in which they were after they were created; and they must have remained forever, and had no end. <sup>23</sup>And they would have had no children; wherefore they would have remained in a state of innocence, having no joy, for they knew no misery; doing no good, for they knew no sin. <sup>24</sup>But behold, all things have been done in the wisdom of him who knoweth all things. <sup>25</sup>Adam fell that men might be; and men are, that they might have joy."),
   ref("Moses 5:10–11","pgp/moses/5","p10-p11","<sup>10</sup>And in that day Adam blessed God and was filled, and began to prophesy concerning all the families of the earth, saying: Blessed be the name of God, for because of my transgression my eyes are opened, and in this life I shall have joy, and again in the flesh I shall see God. <sup>11</sup>And Eve, his wife, heard all these things and was glad, saying: Were it not for our transgression we never should have had seed, and never should have known good and evil, and the joy of our redemption, and the eternal life which God giveth unto all the obedient.")],
 send:[ref("Jeremiah 1:5","ot/jer/1","p5"),ref("Abraham 3:22–26","pgp/abr/3","p22-p26"),ref("D&C 93:29, 33–34","dc-testament/dc/93","p29,p33-p34"),ref("D&C 88:15","dc-testament/dc/88","p15"),ref("1 Corinthians 3:16–17","nt/1-cor/3","p16-p17"),ref("1 Corinthians 6:19–20","nt/1-cor/6","p19-p20"),ref("Genesis 2:16–17","ot/gen/2","p16-p17"),ref("Genesis 3","ot/gen/3"),ref("Alma 42:2–10","bofm/alma/42","p2-p10")],
 dive:"The Catholic Easter Vigil hymn, the Exsultet, contains the line \"O happy fault\" (felix culpa). It is a flicker of the truth Lehi teaches plainly in 2 Nephi 2.",
 ask:"What would your life look like if you believed the body was a prison instead of a temple?",
 why:"If you chose to come here, nothing about your life is random.",
 cmp:{c:"The soul is created by God at conception; there is no life before birth. Adam's sin left every person born with original sin, which baptism removes.",cs:"Catechism 366, 403–405",
  p:"The same: no premortal life, creation from nothing, and inherited sin. Reformed churches call it total depravity.",ps:"Westminster Confession 6; Augsburg Confession II",
  r:"We lived with God before birth and chose to come. The Fall was necessary and good. We answer for our own sins, not Adam's.",rs:"Abraham 3:22–26; 2 Nephi 2:25; Articles of Faith 1:2",
  gap:"Without a premortal life there is no answer to \"why am I here\" beyond \"God decided.\" Without a fortunate Fall the body is something to escape. We know we chose to come."},
 invite:"Will you read all of 2 Nephi 2 this week and write in one sentence why the Fall had to happen?",invite_url:GL+"bofm/2-ne/2?lang=eng",
 promise:"\"Men are, that they might have joy\" (2 Nephi 2:25).",
 share:"We believe you were somebody before you were born, and that you chose this.",
 videos:[["Dallin H. Oaks, The Great Plan of Happiness (Oct 1993)","https://www.churchofjesuschrist.org/study/general-conference/1993/10/the-great-plan-of-happiness?lang=eng"],
  ["David A. Bednar, Ye Are the Temple of God (Oct 2000)","https://www.churchofjesuschrist.org/study/general-conference/2000/10/ye-are-the-temple-of-god?lang=eng"],
  ["Russell M. Nelson, Thanks Be to God (Apr 2012)","https://www.churchofjesuschrist.org/study/general-conference/2012/04/thanks-be-to-god?lang=eng"]],
 quiz:[["Who shouted for joy at the creation of the earth, according to Job 38?",["The angels of the seventh heaven","All the sons of God","The morning watch"],1,"\"All the sons of God shouted for joy\" (Job 38:7)."],
  ["Finish the verse: \"Adam fell that men might be; and men are, that they might have…\"",["peace","joy","knowledge"],1,"Joy (2 Nephi 2:25)."],
  ["Which Article of Faith says we are punished for our own sins and not for Adam's transgression?",["The first","The second","The fourth"],1,"The second Article of Faith."]]},

{n:4,date:"Oct 25",title:"The plan, part 2: why mortality, what comes after, and becoming like Christ",
 anchors:"Preach My Gospel, Lesson 2",
 q:"Is heaven just being with God forever? Then what did Paul mean by \"joint-heirs with Christ\"?",
 a:"Heaven is not the end of growing. Mortality is a test of whether we will do what the Lord commands. After death comes a spirit world, then resurrection, then degrees of glory. The highest of them is exaltation: becoming as God is, joint-heirs with Christ, as Paul said.",
 believe:["Mortality is a test of whether we will do all things the Lord commands (Abraham 3:25).","Agency is how the test works; opposition is required for it.","At death the spirit goes to a spirit world. Everyone will be resurrected.","There are degrees of glory, not a simple heaven and hell.","The purpose is exaltation: to become as God is, joint-heirs with Christ."],
 read:[ref("Abraham 3:24–26","pgp/abr/3","p24-p26","<sup>24</sup>And there stood one among them that was like unto God, and he said unto those who were with him: We will go down, for there is space there, and we will take of these materials, and we will make an earth whereon these may dwell; <sup>25</sup>And we will prove them herewith, to see if they will do all things whatsoever the Lord their God shall command them; <sup>26</sup>And they who keep their first estate shall be added upon; and they who keep not their first estate shall not have glory in the same kingdom with those who keep their first estate; and they who keep their second estate shall have glory added upon their heads for ever and ever."),
   ref("Alma 40:11–12","bofm/alma/40","p11-p12","<sup>11</sup>Now, concerning the state of the soul between death and the resurrection—Behold, it has been made known unto me by an angel, that the spirits of all men, as soon as they are departed from this mortal body, yea, the spirits of all men, whether they be good or evil, are taken home to that God who gave them life. <sup>12</sup>And then shall it come to pass, that the spirits of those who are righteous are received into a state of happiness, which is called paradise, a state of rest, a state of peace, where they shall rest from all their troubles and from all care, and sorrow."),
   ref("1 Corinthians 15:40–42","nt/1-cor/15","p40-p42","<sup>40</sup>There are also celestial bodies, and bodies terrestrial: but the glory of the celestial is one, and the glory of the terrestrial is another. <sup>41</sup>There is one glory of the sun, and another glory of the moon, and another glory of the stars: for one star differeth from another star in glory. <sup>42</sup>So also is the resurrection of the dead."),
   ref("Romans 8:16–17","nt/rom/8","p16-p17","<sup>16</sup>The Spirit itself beareth witness with our spirit, that we are the children of God: <sup>17</sup>And if children, then heirs; heirs of God, and joint-heirs with Christ; if so be that we suffer with him, that we may be also glorified together.")],
 send:[ref("2 Nephi 2:11, 27","bofm/2-ne/2","p11,p27"),ref("Alma 34:32–34","bofm/alma/34","p32-p34"),ref("Alma 12:24","bofm/alma/12","p24"),ref("D&C 76:50–70","dc-testament/dc/76","p50-p70"),ref("D&C 88:22","dc-testament/dc/88","p22"),ref("D&C 138:11–37","dc-testament/dc/138","p11-p37"),ref("Matthew 5:48","nt/matt/5","p48"),ref("3 Nephi 12:48","bofm/3-ne/12","p48"),ref("3 Nephi 27:27","bofm/3-ne/27","p27"),ref("1 John 3:2","nt/1-jn/3","p2"),ref("Revelation 3:21","nt/rev/3","p21"),ref("2 Peter 1:4","nt/2-pet/1","p4"),ref("Moroni 7:48","bofm/moro/7","p48")],
 dive:"The early Church fathers taught what we teach. Irenaeus in the second century and Athanasius in the fourth both wrote that God became man so that man might become divine. Eastern Orthodoxy still calls it theosis. Western Christianity largely let it go.",
 ask:"Why would a loving Father want anything less for His children than what He has?",
 why:"You are training to become, not just to arrive.",
 cmp:{c:"Heaven, hell, and purgatory (a purification before heaven). Heaven is the beatific vision: seeing God face to face.",cs:"Catechism 1023–1032",
  p:"Heaven or hell, no purgatory. Reformed churches add predestination: God chose the saved before the world began.",ps:"Westminster Confession 3, 32–33",
  r:"A spirit world, universal resurrection, and degrees of glory. The highest is exaltation: becoming like God, joint-heirs with Christ.",rs:"Alma 40; D&C 76; Romans 8:17",
  gap:"A heaven where you remain forever a creature beholding a Creator is not the destiny scripture describes (Romans 8:17; Revelation 3:21). The Restoration recovered the end of the plan, not just the middle."},
 invite:"Will you read D&C 76:50–70 and list what the Lord promises to those who receive Him?",invite_url:GL+"dc-testament/dc/76?lang=eng&id=p50-p70#p50",
 promise:"\"All that my Father hath shall be given unto him\" (D&C 84:38).",
 share:"We believe heaven isn't where growing ends; it's where it gets serious.",
 videos:[["Dallin H. Oaks, The Challenge to Become (Oct 2000)","https://www.churchofjesuschrist.org/study/general-conference/2000/10/the-challenge-to-become?lang=eng"],
  ["Gospel Topics Essay: Becoming Like God","https://www.churchofjesuschrist.org/study/manual/gospel-topics-essays/becoming-like-god?lang=eng"],
  ["Russell M. Nelson, Salvation and Exaltation (Apr 2008)","https://www.churchofjesuschrist.org/study/general-conference/2008/04/salvation-and-exaltation?lang=eng"]],
 quiz:[["According to Abraham 3:25, what is the test of mortality?",["Whether we will believe","Whether we will do all things the Lord commands","Whether we will suffer patiently"],1,"\"To see if they will do all things whatsoever the Lord their God shall command them\" (Abraham 3:25)."],
  ["Which section of the Doctrine and Covenants describes the three degrees of glory?",["Section 76","Section 88","Section 138"],0,"Section 76, the Vision."],
  ["Paul says we are heirs of God and…",["servants of Christ","joint-heirs with Christ","friends of Christ"],1,"Joint-heirs with Christ (Romans 8:17)."]]},

{n:5,date:"Nov 1",title:"The Atonement of Jesus Christ",
 anchors:"Gospel Foundations, The Atonement of Jesus Christ; Preach My Gospel, Lessons 2 and 3",
 q:"Faith or works: why has Christianity argued about this for 500 years, and what did Nephi actually say?",
 a:"Nephi said we are saved by grace, and that our part is to be reconciled to God, which Alma's people called repentance. Grace and works were never rivals. Grace saves us and then strengthens us; effort is how we accept it. The Atonement does not only pay for you; it changes you.",
 believe:["Jesus suffered for our sins in Gethsemane and on the cross, and rose the third day.","His Atonement is infinite: it covers the Fall, sin, sorrow, sickness, and weakness.","Resurrection is free to all. Forgiveness requires repentance.","His grace saves us and strengthens us. It does both.","Grace and works are not rivals: we are saved by grace, and grace makes discipleship possible."],
 read:[ref("Alma 7:11–13","bofm/alma/7","p11-p13","<sup>11</sup>And he shall go forth, suffering pains and afflictions and temptations of every kind; and this that the word might be fulfilled which saith he will take upon him the pains and the sicknesses of his people. <sup>12</sup>And he will take upon him death, that he may loose the bands of death which bind his people; and he will take upon him their infirmities, that his bowels may be filled with mercy, according to the flesh, that he may know according to the flesh how to succor his people according to their infirmities."),
   ref("2 Nephi 9:6–10","bofm/2-ne/9","p6-p10"),
   ref("Ephesians 2:8–10","nt/eph/2","p8-p10","<sup>8</sup>For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: <sup>9</sup>Not of works, lest any man should boast. <sup>10</sup>For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them."),
   ref("2 Nephi 25:23","bofm/2-ne/25","p23","<sup>23</sup>For we labor diligently to write, to persuade our children, and also our brethren, to believe in Christ, and to be reconciled to God; for we know that it is by grace that we are saved, after all we can do.")],
 send:[ref("Isaiah 53:3–5","ot/isa/53","p3-p5"),ref("Luke 22:42–44","nt/luke/22","p42-p44"),ref("John 3:16","nt/john/3","p16"),ref("Mosiah 3:7","bofm/mosiah/3","p7"),ref("Alma 24:11","bofm/alma/24","p11"),ref("Alma 34:8–16","bofm/alma/34","p8-p16"),ref("D&C 19:16–19","dc-testament/dc/19","p16-p19"),ref("1 Corinthians 15:20–22","nt/1-cor/15","p20-p22"),ref("Hebrews 4:15–16","nt/heb/4","p15-p16"),ref("2 Nephi 2:6–8","bofm/2-ne/2","p6-p8"),ref("2 Nephi 10:24","bofm/2-ne/10","p24"),ref("Moroni 10:32–33","bofm/moro/10","p32-p33"),ref("James 2:17–26","nt/james/2","p17-p26"),ref("Philippians 2:12","nt/philip/2","p12"),ref("Ether 12:27","bofm/ether/12","p27")],
 dive:"\"After all we can do\" (2 Nephi 25:23) is one of the most misread lines in the Book of Mormon. Read it beside 2 Nephi 10:24 (\"reconcile yourselves… it is only in and through the grace of God that ye are saved\") and Alma 24:11, where \"all we could do\" means repent.",
 ask:"What does grace do for you the day after you're forgiven?",
 why:"Grace is not a transaction you close once; it is the power you live on every day after.",
 cmp:{c:"Christ died for our sins. Grace comes through the sacraments and cooperates with our works across a lifetime.",cs:"Catechism 1996–2005",
  p:"Christ died for our sins. We are justified by faith alone (sola fide); works are the evidence. Many Evangelicals add \"once saved, always saved.\"",ps:"Augsburg Confession IV; Westminster Confession 11",
  r:"Christ suffered in Gethsemane and on the cross. His grace both saves and strengthens; repentance is how we receive it, and it continues all our lives.",rs:"Alma 7:11–12; 2 Nephi 25:23; Ether 12:27",
  gap:"Gethsemane (Luke 22:44; Mosiah 3:7) and the enabling power of grace (Alma 7:11–12; Ether 12:27). The Atonement doesn't only pay for you; it changes you."},
 invite:"Will you repent of one specific thing this week and take the sacrament with it in mind?",invite_url:null,
 promise:"\"Though your sins be as scarlet, they shall be as white as snow\" (Isaiah 1:18).",
 share:"We believe Christ suffered in a garden as well as on a cross, so He knows exactly what you're carrying.",
 videos:[["Jeffrey R. Holland, Where Justice, Love, and Mercy Meet (Apr 2015)","https://www.churchofjesuschrist.org/study/general-conference/2015/04/where-justice-love-and-mercy-meet?lang=eng"],
  ["Dieter F. Uchtdorf, The Gift of Grace (Apr 2015)","https://www.churchofjesuschrist.org/study/general-conference/2015/04/the-gift-of-grace?lang=eng"],
  ["Brad Wilcox, His Grace Is Sufficient (BYU devotional, 2011)","https://speeches.byu.edu/talks/brad-wilcox/his-grace-is-sufficient/"],
  ["David A. Bednar, Bear Up Their Burdens with Ease (Apr 2014)","https://www.churchofjesuschrist.org/study/general-conference/2014/04/bear-up-their-burdens-with-ease?lang=eng"]],
 quiz:[["According to Alma 7:12, why did Christ take upon Him our infirmities?",["To prove He was God","So He would know how to succor His people","To satisfy the law of Moses"],1,"\"That he may know according to the flesh how to succor his people according to their infirmities\" (Alma 7:12)."],
  ["In Alma 24:11, what was \"all we could do\"?",["Fight","Pray","Repent"],2,"Repent of their sins (Alma 24:11)."],
  ["Where, besides the cross, does the Book of Mormon say Christ suffered for sin?",["The temple","Gethsemane","The wilderness"],1,"Gethsemane; see Mosiah 3:7 and D&C 19:18."]]},

{n:6,date:"Nov 8",title:"The doctrine of Christ",
 anchors:"Preach My Gospel, Lesson 3; Gospel Foundations, Obedience to God's Commandments",
 q:"Why was Jesus baptized if He had no sins to wash away, and who had the right to do it?",
 a:"He was baptized to fulfil all righteousness: to show the gate and to keep the commandment Himself. And He walked to the one man on earth who held the authority to do it, John. Baptism is a covenant made with someone holding God's authority, which is why authority, accountability, and the gift of the Holy Ghost all matter.",
 believe:["Faith in Jesus Christ, repentance, baptism by immersion by one with authority, the gift of the Holy Ghost by the laying on of hands, and enduring to the end (Articles of Faith 1:4).","Baptism is a covenant, not only a symbol, so it requires accountability (age eight) and authority.","The gift of the Holy Ghost is conferred, not assumed.","Enduring means repeating the cycle every week at the sacrament table."],
 read:[ref("3 Nephi 11:31–39","bofm/3-ne/11","p31-p39"),
   ref("Acts 2:37–38","nt/acts/2","p37-p38","<sup>37</sup>Now when they heard this, they were pricked in their heart, and said unto Peter and to the rest of the apostles, Men and brethren, what shall we do? <sup>38</sup>Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost."),
   ref("Moroni 8:8–12","bofm/moro/8","p8-p12")],
 send:[ref("2 Nephi 31:5–21","bofm/2-ne/31","p5-p21"),ref("3 Nephi 27:13–21","bofm/3-ne/27","p13-p21"),ref("John 3:5","nt/john/3","p5"),ref("Matthew 3:13–17","nt/matt/3","p13-p17"),ref("Mark 1:9–10","nt/mark/1","p9-p10"),ref("Romans 6:3–5","nt/rom/6","p3-p5"),ref("Acts 8:14–17","nt/acts/8","p14-p17"),ref("Acts 19:1–6","nt/acts/19","p1-p6"),ref("Mosiah 18:8–10","bofm/mosiah/18","p8-p10"),ref("D&C 20:37","dc-testament/dc/20","p37"),ref("D&C 22","dc-testament/dc/22"),ref("D&C 68:25–27","dc-testament/dc/68","p25-p27")],
 dive:"Christ Himself calls this \"my doctrine\" and says anything more or less than it \"cometh of evil\" (3 Nephi 11:39–40). It is simple enough for a child.",
 ask:"Which of the five steps do people skip most, and why?",
 why:"These five steps are the only path Christ Himself called \"my doctrine.\"",
 cmp:{c:"Infants are baptized, by pouring, to remove original sin. Confirmation is a separate later sacrament. Seven sacraments in all.",cs:"Catechism 1213, 1250, 1285",
  p:"Lutherans, Presbyterians, Anglicans, and Methodists baptize infants as a covenant sign. Baptists and most Evangelicals baptize believers by immersion, as a sign of a salvation already received by faith, not as a requirement.",ps:"Westminster Confession 28; Baptist Faith and Message VII",
  r:"Baptism by immersion, at the age of accountability, by one holding authority, followed by the gift of the Holy Ghost by the laying on of hands.",rs:"3 Nephi 11:33–39; Acts 8:14–17; D&C 68:25–27",
  gap:"Authority and covenant. Baptism as an ordinance administered by one holding keys, to an accountable person, followed by the gift of the Holy Ghost by the laying on of hands. That full pattern exists in one Church."},
 invite:"Will you write your baptismal covenant in three lines from Mosiah 18:8–10 and read it before the sacrament?",invite_url:GL+"bofm/mosiah/18?lang=eng&id=p8-p10#p8",
 promise:"\"That they may always have his Spirit to be with them\" (Moroni 4:3).",
 share:"We believe baptism is a promise you make on purpose, at an age when you can mean it.",
 videos:[["D. Todd Christofferson, The Doctrine of Christ (Apr 2012)","https://www.churchofjesuschrist.org/study/general-conference/2012/04/the-doctrine-of-christ?lang=eng"],
  ["David A. Bednar, Always Retain a Remission of Your Sins (Apr 2016)","https://www.churchofjesuschrist.org/study/general-conference/2016/04/always-retain-a-remission-of-your-sins?lang=eng"],
  ["Gospel Topics: Baptism","https://www.churchofjesuschrist.org/study/manual/gospel-topics/baptism?lang=eng"]],
 quiz:[["Which chapter records the risen Christ teaching His doctrine to the Nephites?",["3 Nephi 11","3 Nephi 18","Moroni 8"],0,"3 Nephi 11:31–40."],
  ["What did Peter tell the crowd to do in Acts 2:38?",["Believe and be saved","Repent and be baptized","Sell all and follow"],1,"\"Repent, and be baptized every one of you in the name of Jesus Christ\" (Acts 2:38)."],
  ["At what age does the Lord say children become accountable?",["Six","Eight","Twelve"],1,"Eight years old (D&C 68:25–27)."]]},

{n:7,date:"Nov 15",title:"Personal revelation: how truth is known",
 anchors:"Gospel Foundations, Personal Revelation Through the Holy Ghost; Preach My Gospel, chapter 4 and Lesson 1",
 q:"Did God stop talking when the last apostle died?",
 a:"No. He speaks to a prophet for the whole Church and to each of us for our own lives. The Holy Ghost teaches and confirms truth, usually quietly, in thoughts and feelings and peace. Revelation is a skill you can practice: ask, study it out, act, and learn to recognize the answer.",
 believe:["God speaks today, to prophets for the Church and to each of us for our lives.","The Holy Ghost teaches and confirms truth, usually quietly: thoughts, feelings, peace.","Revelation is a skill: ask, study it out, act, recognize.","Testimony grows by experiment (Alma 32), not by argument."],
 read:[ref("Moroni 10:3–5","bofm/moro/10","p3-p5","<sup>4</sup>And when ye shall receive these things, I would exhort you that ye would ask God, the Eternal Father, in the name of Christ, if these things are not true; and if ye shall ask with a sincere heart, with real intent, having faith in Christ, he will manifest the truth of it unto you, by the power of the Holy Ghost. <sup>5</sup>And by the power of the Holy Ghost ye may know the truth of all things."),
   ref("D&C 8:2–3 and 9:7–9","dc-testament/dc/8","p2-p3","<sup>2</sup>Yea, behold, I will tell you in your mind and in your heart, by the Holy Ghost, which shall come upon you and which shall dwell in your heart. <sup>3</sup>Now, behold, this is the spirit of revelation…"),
   ref("1 Kings 19:11–12","ot/1-kgs/19","p11-p12","<sup>12</sup>And after the earthquake a fire; but the Lord was not in the fire: and after the fire a still small voice.")],
 send:[ref("James 1:5–6","nt/james/1","p5-p6"),ref("John 14:26","nt/john/14","p26"),ref("John 16:13","nt/john/16","p13"),ref("D&C 9:7–9","dc-testament/dc/9","p7-p9"),ref("1 Corinthians 2:9–14","nt/1-cor/2","p9-p14"),ref("Galatians 5:22–23","nt/gal/5","p22-p23"),ref("Alma 32:26–43","bofm/alma/32","p26-p43"),ref("Alma 5:45–46","bofm/alma/5","p45-p46"),ref("Enos 1:1–8","bofm/enos/1","p1-p8"),ref("Helaman 5:30","bofm/hel/5","p30"),ref("2 Nephi 32:2–5","bofm/2-ne/32","p2-p5"),ref("D&C 6:22–23","dc-testament/dc/6","p22-p23"),ref("D&C 42:14","dc-testament/dc/42","p14"),ref("D&C 50:17–22","dc-testament/dc/50","p17-p22"),ref("D&C 88:118","dc-testament/dc/88","p118"),ref("D&C 130:22–23","dc-testament/dc/130","p22-p23")],
 dive:"Preach My Gospel, chapter 10, says people may be persuaded of truths, but to be converted they need experiences with the Spirit. That is the entire missionary method, and it works on you first.",
 ask:"When did you last feel something you would call revelation, and how did you know?",
 why:"If God will answer you, you never have to borrow anyone else's testimony.",
 cmp:{c:"Public revelation ended with the death of the last apostle. The Church's teaching office interprets it. Private revelation can happen but adds nothing binding.",cs:"Catechism 66–67, 85–86",
  p:"The Bible alone is the final authority. The Spirit illuminates scripture but gives no new revelation. Many Reformed and Baptist churches teach that the gifts of the Spirit ceased with the apostles.",ps:"Westminster Confession 1.6",
  r:"God speaks today, through a living prophet for the Church and through the Holy Ghost to every person who asks in faith.",rs:"Moroni 10:4–5; D&C 8:2–3; James 1:5",
  gap:"An open heaven. We don't only believe God spoke; we believe He speaks, to a prophet and to you."},
 invite:"Will you ask one specific question in prayer this week, study it out, and write down what came?",invite_url:null,
 promise:"\"I will tell you in your mind and in your heart\" (D&C 8:2).",
 share:"We believe you can ask God a question and get an answer.",
 videos:[["Russell M. Nelson, Revelation for the Church, Revelation for Our Lives (Apr 2018)","https://www.churchofjesuschrist.org/study/general-conference/2018/04/revelation-for-the-church-revelation-for-our-lives?lang=eng"],
  ["David A. Bednar, The Spirit of Revelation (Apr 2011)","https://www.churchofjesuschrist.org/study/general-conference/2011/04/the-spirit-of-revelation?lang=eng"],
  ["David A. Bednar, Receive the Holy Ghost (Oct 2010)","https://www.churchofjesuschrist.org/study/general-conference/2010/10/receive-the-holy-ghost?lang=eng"]],
 quiz:[["Moroni 10:4 says the Holy Ghost will manifest the truth to those who ask with what?",["A loud voice","A sincere heart, real intent, and faith in Christ","A written record"],1,"\"With a sincere heart, with real intent, having faith in Christ\" (Moroni 10:4)."],
  ["According to D&C 8:2, where does the Lord say He will tell you?",["In a dream","In your mind and in your heart","Through a prophet only"],1,"\"In your mind and in your heart\" (D&C 8:2)."],
  ["Where was the Lord found in 1 Kings 19?",["In the wind","In the earthquake","In a still small voice"],2,"In a still small voice (1 Kings 19:12)."]]},

{n:8,date:"Nov 22",title:"Scriptures, prophets, and the Book of Mormon",
 anchors:"Gospel Foundations, Scriptures and Prophets Teach of Jesus Christ; Preach My Gospel, chapter 5 and Lesson 1",
 q:"Who decided what went in the Bible, and why would God stop at 66 books?",
 a:"Councils and centuries decided the Bible's table of contents; God never said He was finished. The Bible names books we don't have, and it warns against adding to Moses' words long before it warns against adding to John's. The Book of Mormon is God's own answer, and it comes with a test anyone can run.",
 believe:["The Bible is the word of God as far as it is translated correctly; the Book of Mormon is also the word of God (Articles of Faith 1:8).","The canon is open: God has revealed and will yet reveal many great and important things (Articles of Faith 1:9).","Living prophets speak for God today.","The Book of Mormon is the evidence of the Restoration: if it is true, Joseph Smith was a prophet."],
 read:[ref("2 Nephi 29:3–10","bofm/2-ne/29","p3-p10"),
   ref("Ezekiel 37:15–19","ot/ezek/37","p15-p19"),
   ref("Revelation 22:18–19, Deuteronomy 4:2, and 12:32","nt/rev/22","p18-p19","<sup>Rev 22:18</sup>For I testify unto every man that heareth the words of the prophecy of this book, If any man shall add unto these things, God shall add unto him the plagues that are written in this book. <sup>Deut 4:2</sup>Ye shall not add unto the word which I command you, neither shall ye diminish ought from it… <sup>Deut 12:32</sup>What thing soever I command you, observe to do it: thou shalt not add thereto, nor diminish from it.")],
 send:[ref("Amos 3:7","ot/amos/3","p7"),ref("Isaiah 29:11–18","ot/isa/29","p11-p18"),ref("John 10:16","nt/john/10","p16"),ref("3 Nephi 15:21","bofm/3-ne/15","p21"),ref("2 Timothy 3:16","nt/2-tim/3","p16"),ref("2 Peter 1:20–21","nt/2-pet/1","p20-p21"),ref("D&C 1:37–38","dc-testament/dc/1","p37-p38"),ref("D&C 21:4–6","dc-testament/dc/21","p4-p6"),ref("D&C 68:4","dc-testament/dc/68","p4"),ref("Book of Mormon title page","bofm/bofm-title"),ref("Moroni 10:3–5","bofm/moro/10","p3-p5"),ref("Joshua 10:13","ot/josh/10","p13"),ref("Colossians 4:16","nt/col/4","p16")],
 dive:"The \"don't add to this book\" objection collapses on its own terms. Moses gave the same warning in Deuteronomy, and the Bible kept growing for a thousand years after him. The Bible also names books we don't have (Joshua 10:13; Colossians 4:16; Jude 1:14).",
 ask:"Who decided which books went in the Bible, and by what authority?",
 why:"A closed canon closes the door on the very God who gave you the Bible.",
 cmp:{c:"Scripture (73 books) together with sacred Tradition, interpreted by the Church's teaching office. The canon is closed.",cs:"Catechism 80–82, 120",
  p:"Scripture alone (66 books) is sufficient. Many Evangelicals hold it inerrant in the original manuscripts. The canon is closed and there is no living prophet.",ps:"Westminster Confession 1; Chicago Statement, 1978",
  r:"An open canon. The Bible and the Book of Mormon are both the word of God, and God continues to reveal through living prophets.",rs:"Articles of Faith 1:8–9; 2 Nephi 29; D&C 1:38",
  gap:"A closed canon is a claim that God has stopped talking. The Book of Mormon is the proof He hasn't, and it is a proof anyone can test (Moroni 10:4)."},
 invite:"Will you read the Book of Mormon's title page and introduction, then one chapter a day this week?",invite_url:GL+"bofm/bofm-title?lang=eng",
 promise:"President Nelson promised better decisions every day (Oct 2017).",
 share:"We believe God is still writing.",
 videos:[["Jeffrey R. Holland, My Words… Never Cease (Apr 2008)","https://www.churchofjesuschrist.org/study/general-conference/2008/04/my-words-never-cease?lang=eng"],
  ["Jeffrey R. Holland, Safety for the Soul (Oct 2009)","https://www.churchofjesuschrist.org/study/general-conference/2009/10/safety-for-the-soul?lang=eng"],
  ["Tad R. Callister, The Book of Mormon: Man-Made or God-Given? (BYU devotional, 2016)","https://speeches.byu.edu/talks/tad-r-callister/book-mormon-man-made-god-given/"],
  ["Russell M. Nelson, The Book of Mormon: What Would Your Life Be Like without It? (Oct 2017)","https://www.churchofjesuschrist.org/study/general-conference/2017/10/the-book-of-mormon-what-would-your-life-be-like-without-it?lang=eng"]],
 quiz:[["Which Old Testament book contains the same \"do not add to it\" warning as Revelation 22?",["Deuteronomy","Psalms","Isaiah"],0,"Deuteronomy 4:2 and 12:32."],
  ["In Ezekiel 37, what becomes one in the prophet's hand?",["Two swords","Two sticks","Two scrolls of law"],1,"The stick of Judah and the stick of Joseph become one (Ezekiel 37:15–19)."],
  ["Which Article of Faith says God \"will yet reveal many great and important things\"?",["The eighth","The ninth","The tenth"],1,"The ninth Article of Faith."]]},

{n:9,date:"Nov 29",title:"Covenants, the Sabbath, and the sacrament",
 anchors:"Gospel Foundations, The Sabbath Day and the Sacrament, and Obedience to God's Commandments; Preach My Gospel, Lesson 4",
 q:"What actually happens to the bread, and why does it matter who blesses it?",
 a:"The bread stays bread. What changes is you. The sacrament is a covenant renewed: you witness that you are willing, and God promises His Spirit. It is administered by priesthood authority because it is an ordinance, not only a memorial, and the promise attached to it is God's to make.",
 believe:["A covenant is a two-way promise; God binds Himself when we keep our part (D&C 82:10).","Commandments are how we show love, not how we earn it (John 14:15).","The Sabbath is a sign between us and God (Exodus 31:13).","The sacrament renews the baptismal covenant every week and is administered by priesthood authority."],
 read:[ref("Mosiah 5:5–8","bofm/mosiah/5","p5-p8"),
   ref("3 Nephi 18:1–12","bofm/3-ne/18","p1-p12"),
   ref("Isaiah 58:13–14","ot/isa/58","p13-p14","<sup>13</sup>If thou turn away thy foot from the sabbath, from doing thy pleasure on my holy day; and call the sabbath a delight, the holy of the Lord, honourable; and shalt honour him, not doing thine own ways, nor finding thine own pleasure, nor speaking thine own words: <sup>14</sup>Then shalt thou delight thyself in the Lord…")],
 send:[ref("Exodus 20:8–11","ot/ex/20","p8-p11"),ref("Exodus 31:13","ot/ex/31","p13"),ref("Mark 2:27","nt/mark/2","p27"),ref("Luke 22:19–20","nt/luke/22","p19-p20"),ref("1 Corinthians 11:23–29","nt/1-cor/11","p23-p29"),ref("Moroni 4","bofm/moro/4"),ref("Moroni 5","bofm/moro/5"),ref("D&C 20:77, 79","dc-testament/dc/20","p77,p79"),ref("D&C 59:9–13","dc-testament/dc/59","p9-p13"),ref("D&C 82:10","dc-testament/dc/82","p10"),ref("D&C 130:20–21","dc-testament/dc/130","p20-p21"),ref("John 14:15","nt/john/14","p15"),ref("Mosiah 2:41","bofm/mosiah/2","p41"),ref("Mosiah 18:8–10","bofm/mosiah/18","p8-p10")],
 dive:"The sacrament prayers are among the few fixed-wording prayers in the Church, and they are covenant language: \"witness… that they are willing.\" Read Moroni 4:3 slowly and count the promises on each side.",
 ask:"What are you actually saying yes to every Sunday?",
 why:"Every Sunday you either renew a covenant or you just eat bread.",
 cmp:{c:"The bread and wine become the body and blood of Christ (transubstantiation, defined in 1215). The Mass is a sacrifice offered by a priest.",cs:"Catechism 1374–1377",
  p:"Lutherans: Christ is truly present in, with, and under the bread. Reformed: a spiritual presence. Baptists and most Evangelicals: a memorial only. All observe Sunday; Adventists keep Saturday.",ps:"Augsburg Confession X; Westminster Confession 29",
  r:"The bread and water are emblems. The sacrament is a weekly renewal of the baptismal covenant, administered by priesthood authority, with the promise of His Spirit.",rs:"Moroni 4–5; 3 Nephi 18; D&C 20:77, 79",
  gap:"The sacrament as covenant renewal, a weekly ordinance by authority that promises \"his Spirit to be with you,\" is a restored idea. Other Christians remember; we re-covenant."},
 invite:"Will you arrive before the sacrament this Sunday and read Moroni 4 and 5 before it is passed?",invite_url:GL+"bofm/moro/4?lang=eng",
 promise:"\"That they may always have his Spirit to be with them\" (D&C 20:77).",
 share:"We believe the sacrament is a promise renewed, not a memory observed.",
 videos:[["Russell M. Nelson, The Sabbath Is a Delight (Apr 2015)","https://www.churchofjesuschrist.org/study/general-conference/2015/04/the-sabbath-is-a-delight?lang=eng"],
  ["Dallin H. Oaks, The Aaronic Priesthood and the Sacrament (Oct 2008)","https://www.churchofjesuschrist.org/study/general-conference/2008/10/the-aaronic-priesthood-and-the-sacrament?lang=eng"],
  ["Dale G. Renlund, Choose You This Day (Oct 2018)","https://www.churchofjesuschrist.org/study/general-conference/2018/10/choose-you-this-day?lang=eng"]],
 quiz:[["In the sacrament prayer on the bread, what do we witness we are willing to do?",["Take upon us His name, always remember Him, keep His commandments","Fast, pray, and pay tithing","Attend the temple monthly"],0,"Moroni 4:3; D&C 20:77."],
  ["What does Exodus 31:13 call the Sabbath?",["A rest","A sign","A feast"],1,"\"It is a sign between me and you\" (Exodus 31:13)."],
  ["D&C 82:10 says the Lord is bound when we do what?",["Believe","Pray","Do what He says"],2,"\"I, the Lord, am bound when ye do what I say\" (D&C 82:10)."]]},

{n:10,date:"Dec 6",title:"The temple, eternal families, and our ancestors",
 anchors:"Gospel Foundations, The Covenants and Ordinances of the Temple, and Making the Blessings of the Gospel Available to Our Deceased Ancestors; Preach My Gospel, Lesson 4",
 q:"What happens to the billions who never heard of Jesus, and does \"till death do us part\" mean it?",
 a:"Everyone will hear the gospel, in this life or the next, and the living perform the ordinances for those who could not. Elijah restored the keys that seal families beyond death, so \"till death do us part\" is not the last word. God's justice has a mechanism, and His love has a sealing.",
 believe:["God is just. Every person will hear the gospel, in this life or the next.","Ordinances are required for all, so the living perform them for the dead.","Elijah restored sealing keys. Families can be bound forever.","The temple is where we make the covenants that lead to exaltation."],
 read:[ref("1 Corinthians 15:29","nt/1-cor/15","p29","<sup>29</sup>Else what shall they do which are baptized for the dead, if the dead rise not at all? why are they then baptized for the dead?"),
   ref("1 Peter 3:18–20 and 4:6","nt/1-pet/3","p18-p20","<sup>3:19</sup>By which also he went and preached unto the spirits in prison; <sup>4:6</sup>For for this cause was the gospel preached also to them that are dead, that they might be judged according to men in the flesh, but live according to God in the spirit."),
   ref("Malachi 4:5–6 and D&C 2","ot/mal/4","p5-p6","<sup>5</sup>Behold, I will send you Elijah the prophet before the coming of the great and dreadful day of the Lord: <sup>6</sup>And he shall turn the heart of the fathers to the children, and the heart of the children to their fathers, lest I come and smite the earth with a curse.")],
 send:[ref("D&C 2","dc-testament/dc/2"),ref("D&C 110:13–16","dc-testament/dc/110","p13-p16"),ref("D&C 128:15–18","dc-testament/dc/128","p15-p18"),ref("D&C 138:29–37, 57–59","dc-testament/dc/138","p29-p37,p57-p59"),ref("John 5:25–29","nt/john/5","p25-p29"),ref("Matthew 16:19","nt/matt/16","p19"),ref("Matthew 19:4–6","nt/matt/19","p4-p6"),ref("Matthew 22:23–30","nt/matt/22","p23-p30"),ref("D&C 131:1–4","dc-testament/dc/131","p1-p4"),ref("D&C 132:19","dc-testament/dc/132","p19"),ref("Isaiah 2:2–3","ot/isa/2","p2-p3"),ref("Obadiah 1:21","ot/obad/1","p21"),ref("Hebrews 11:40","nt/heb/11","p40"),ref("D&C 97:15–16","dc-testament/dc/97","p15-p16")],
 dive:"1 Corinthians 15:29 is a verse most Christians have no use for. Paul treats baptism for the dead as a practice his readers already know, and uses it to argue for the resurrection.",
 ask:"If a loving God requires baptism, what must He also provide for the billions who never had the chance?",
 why:"God's justice needs a mechanism and His love needs a sealing; the temple is both.",
 cmp:{c:"Prayers for the dead and purgatory, but no ordinances for them. Marriage is a sacrament that ends at death. \"Limbo\" for unbaptized infants was never defined; a 2007 Vatican study expressed hope instead.",cs:"Catechism 1030–1032, 1638–1640; 2 Maccabees 12",
  p:"Those who never heard are left to God's mercy or judgment, with no mechanism. Marriage vows end \"till death us do part\" (Book of Common Prayer, 1549). Matthew 22:30 is read as ending marriage at death.",ps:"Westminster Confession 24",
  r:"The gospel is preached in the spirit world; the living perform ordinances for the dead; sealing keys bind families for eternity.",rs:"1 Peter 4:6; 1 Corinthians 15:29; D&C 128; 132:19",
  gap:"A mechanism for God's justice (vicarious ordinances) and a sealing for God's love (Elijah's keys). We are the only Christians whose answer to \"what about my grandmother\" is an address."},
 invite:"Will you find one ancestor on FamilySearch this week who needs an ordinance, and plan a temple trip?",invite_url:"https://www.familysearch.org/",
 promise:"The hearts of the children turn to their fathers (Malachi 4:6).",
 share:"We believe no one is lost because of when or where they were born.",
 videos:[["David A. Bednar, The Hearts of the Children Shall Turn (Oct 2011)","https://www.churchofjesuschrist.org/study/general-conference/2011/10/the-hearts-of-the-children-shall-turn?lang=eng"],
  ["Dale G. Renlund, Family History and Temple Work: Sealing and Healing (Apr 2018)","https://www.churchofjesuschrist.org/study/general-conference/2018/04/family-history-and-temple-work-sealing-and-healing?lang=eng"],
  ["Russell M. Nelson, The Temple and Your Spiritual Foundation (Oct 2021)","https://www.churchofjesuschrist.org/study/general-conference/2021/10/47nelson?lang=eng"]],
 quiz:[["Which New Testament verse mentions baptism for the dead?",["Romans 6:4","1 Corinthians 15:29","Hebrews 11:40"],1,"1 Corinthians 15:29."],
  ["Who restored the sealing keys in the Kirtland Temple?",["Moses","Elias","Elijah"],2,"Elijah (D&C 110:13–16)."],
  ["According to 1 Peter 4:6, why was the gospel preached to the dead?",["So they could be judged as men in the flesh and live according to God in the spirit","So they could return to earth","So they could become angels"],0,"1 Peter 4:6."]]},

{n:11,date:"Dec 13",title:"Becoming like Him: Christlike attributes, service, and sacrifice",
 anchors:"Preach My Gospel, chapter 6; Gospel Foundations, Caring for Those in Need, and Sacrifice: Tithes and Offerings",
 q:"What does \"be ye therefore perfect\" mean if perfection is impossible?",
 a:"The word translated \"perfect\" means complete, finished, whole. It is a direction, not a demand for today. Christ commands it because His grace makes it possible over time, and we move toward it by taking on His attributes, serving, and sacrificing. Holiness is not only preparation to be with God; it is becoming like Him.",
 believe:["Discipleship is becoming, not only believing: faith, hope, charity, virtue, knowledge, patience, humility, diligence, obedience (Preach My Gospel, chapter 6).","Service is how we become like Him: \"when ye are in the service of your fellow beings.\"","Sacrifice, whether tithing, fasting, or time, is the school of becoming.","Grace makes the change possible; effort is how we accept it."],
 read:[ref("2 Peter 1:4–8","nt/2-pet/1","p4-p8"),
   ref("Mosiah 3:19","bofm/mosiah/3","p19","<sup>19</sup>For the natural man is an enemy to God, and has been from the fall of Adam, and will be, forever and ever, unless he yields to the enticings of the Holy Spirit, and putteth off the natural man and becometh a saint through the atonement of Christ the Lord, and becometh as a child, submissive, meek, humble, patient, full of love, willing to submit to all things which the Lord seeth fit to inflict upon him, even as a child doth submit to his father."),
   ref("Moroni 7:45–48","bofm/moro/7","p45-p48","<sup>48</sup>Wherefore, my beloved brethren, pray unto the Father with all the energy of heart, that ye may be filled with this love, which he hath bestowed upon all who are true followers of his Son, Jesus Christ; that ye may become the sons of God; that when he shall appear we shall be like him, for we shall see him as he is; that we may have this hope; that we may be purified even as he is pure. Amen.")],
 send:[ref("Alma 7:23–24","bofm/alma/7","p23-p24"),ref("D&C 4:5–6","dc-testament/dc/4","p5-p6"),ref("Mosiah 2:17","bofm/mosiah/2","p17"),ref("Mosiah 4:26","bofm/mosiah/4","p26"),ref("Matthew 25:34–40","nt/matt/25","p34-p40"),ref("James 1:27","nt/james/1","p27"),ref("3 Nephi 27:27","bofm/3-ne/27","p27"),ref("Alma 34:28","bofm/alma/34","p28"),ref("Isaiah 58:6–11","ot/isa/58","p6-p11"),ref("Malachi 3:8–10","ot/mal/3","p8-p10"),ref("3 Nephi 12:48","bofm/3-ne/12","p48"),ref("Alma 5:14","bofm/alma/5","p14"),ref("Moroni 10:32","bofm/moro/10","p32"),ref("Philippians 4:13","nt/philip/4","p13")],
 dive:"Preach My Gospel, chapter 6, has a self-assessment on every attribute. Try one, silently, for thirty seconds.",
 ask:"Which attribute did the Savior have to develop, and which one is God working on in you?",
 why:"Holiness that ends at \"being with God\" stops short of what He wants for you.",
 cmp:{c:"The works of mercy and the pursuit of holiness prepare a person for heaven. Sainthood is the model.",cs:"Catechism 2013, 2447",
  p:"Sanctification follows justification; good works are the fruit of faith. Methodists speak of \"Christian perfection.\"",ps:"Westminster Confession 13; Wesley, A Plain Account",
  r:"Discipleship is becoming like Christ, attribute by attribute, until \"when he shall appear we shall be like him.\"",rs:"Moroni 7:48; 3 Nephi 27:27; 2 Peter 1:4",
  gap:"Lead with common ground: this is shared Christianity at its best. The difference is the end of the process. For most Christians holiness prepares you to be with God; for us it prepares you to be like Him. Same road, farther destination."},
 invite:"Will you pick one attribute, one action, and do it three times before Christmas?",invite_url:"https://www.churchofjesuschrist.org/study/manual/preach-my-gospel-2023/14-chapter-6?lang=eng",
 promise:"\"Charity never faileth\" (Moroni 7:46).",
 share:"We believe the goal isn't only heaven; it's becoming like the One who lives there.",
 videos:[["David A. Bednar, Converted unto the Lord (Oct 2012)","https://www.churchofjesuschrist.org/study/general-conference/2012/10/converted-unto-the-lord?lang=eng"],
  ["Dale G. Renlund, Latter-day Saints Keep on Trying (Apr 2015)","https://www.churchofjesuschrist.org/study/general-conference/2015/04/latter-day-saints-keep-on-trying?lang=eng"],
  ["David A. Bednar, The Windows of Heaven (Oct 2013)","https://www.churchofjesuschrist.org/study/general-conference/2013/10/the-windows-of-heaven?lang=eng"]],
 quiz:[["Mosiah 3:19 says the natural man becomes a saint through what?",["Obedience alone","The atonement of Christ the Lord","Fasting and prayer"],1,"\"Through the atonement of Christ the Lord\" (Mosiah 3:19)."],
  ["Moroni 7:48 promises that when He appears, we shall be…",["forgiven","like him","judged"],1,"\"We shall be like him, for we shall see him as he is\" (Moroni 7:48)."],
  ["Which Book of Mormon king said that serving others is serving God?",["Nephi","Benjamin","Mosiah"],1,"King Benjamin (Mosiah 2:17)."]]},

{n:12,date:"Dec 27",title:"Inviting all: the Light of the World",
 anchors:"Gospel Foundations, Inviting All to Receive the Gospel of Jesus Christ; Preach My Gospel, chapters 1, 9, and 10",
 q:"If every church shares Jesus, what exactly are we inviting people to?",
 a:"Not a better church. The restored one: God's authority, a Father with a body, a chosen mortality, an open heaven, an open canon, covenant renewal, ordinances for the dead, and a plan that ends in becoming like Him. Sharing that is invitation, not argument.",
 believe:["Every member has a covenant obligation to share (D&C 88:81).","The worth of souls is great (D&C 18:10–16).","Sharing is invitation, not argument; testimony, not proof.","We have something no one else has: a restored Church, authority, an open heaven, and a plan that ends in exaltation."],
 read:[ref("D&C 4","dc-testament/dc/4",null,"<sup>1</sup>Now behold, a marvelous work is about to come forth among the children of men. <sup>2</sup>Therefore, O ye that embark in the service of God, see that ye serve him with all your heart, might, mind and strength, that ye may stand blameless before God at the last day. <sup>3</sup>Therefore, if ye have desires to serve God ye are called to the work…"),
   ref("D&C 18:10–16","dc-testament/dc/18","p10-p16","<sup>10</sup>Remember the worth of souls is great in the sight of God; … <sup>15</sup>And if it so be that you should labor all your days in crying repentance unto this people, and bring, save it be one soul unto me, how great shall be your joy with him in the kingdom of my Father! <sup>16</sup>And now, if your joy will be great with one soul that you have brought unto me into the kingdom of my Father, how great will be your joy if you should bring many souls unto me!"),
   ref("1 Peter 3:15","nt/1-pet/3","p15","<sup>15</sup>But sanctify the Lord God in your hearts: and be ready always to give an answer to every man that asketh you a reason of the hope that is in you with meekness and fear:")],
 send:[ref("Matthew 5:14–16","nt/matt/5","p14-p16"),ref("Matthew 28:19–20","nt/matt/28","p19-p20"),ref("Mark 16:15","nt/mark/16","p15"),ref("Alma 26:1–16","bofm/alma/26","p1-p16"),ref("Mosiah 28:3","bofm/mosiah/28","p3"),ref("Alma 17:2–3","bofm/alma/17","p2-p3"),ref("Romans 1:16","nt/rom/1","p16"),ref("3 Nephi 5:13","bofm/3-ne/5","p13"),ref("3 Nephi 18:24","bofm/3-ne/18","p24"),ref("John 8:12","nt/john/8","p12"),ref("Isaiah 9:2, 6","ot/isa/9","p2,p6"),ref("D&C 88:81","dc-testament/dc/88","p81"),ref("D&C 123:12","dc-testament/dc/123","p12"),ref("Mosiah 18:9","bofm/mosiah/18","p9")],
 dive:"Walk the whole arc in five minutes, one sentence per week. Restoration and authority. A Father with a body. A chosen mortality and a fortunate Fall. Exaltation. Gethsemane and enabling grace. Covenant baptism and the gift of the Holy Ghost. An open heaven. An open canon. Covenant renewal. Ordinances for the dead and eternal families. Becoming like Him.",
 ask:"Which of these would you most want a friend to know?",
 why:"What you have was restored at a price; keeping it to yourself wastes it.",
 cmp:{c:"The Great Commission belongs to the whole Church; evangelization is every Catholic's task.",cs:"Catechism 849–856",
  p:"The Great Commission is central; sharing the gospel is every believer's duty.",ps:"Matthew 28:19–20",
  r:"The same commission, with a restored message: authority, ordinances, and a plan that ends in exaltation.",rs:"D&C 4; 18:10–16; 88:81",
  gap:"Every Christian church takes the Great Commission seriously. The difference is what we are inviting people to. Not a better church; the restored one."},
 invite:"Will you pick one person and share one thing from this class with them before New Year's?",invite_url:null,
 promise:"\"How great shall be your joy\" (D&C 18:16).",
 share:"We're not inviting you to a better church. We're inviting you to the restored one.",
 videos:[["Dieter F. Uchtdorf, Missionary Work: Sharing What Is in Your Heart (Apr 2019)","https://www.churchofjesuschrist.org/study/general-conference/2019/04/36uchtdorf?lang=eng"],
  ["Dallin H. Oaks, Sharing the Restored Gospel (Oct 2016)","https://www.churchofjesuschrist.org/study/general-conference/2016/10/sharing-the-restored-gospel?lang=eng"],
  ["Russell M. Nelson, Preaching the Gospel of Peace (Apr 2022)","https://www.churchofjesuschrist.org/study/general-conference/2022/04/12nelson?lang=eng"],
  ["Jeffrey R. Holland, Witnesses unto Me (Apr 2001)","https://www.churchofjesuschrist.org/study/general-conference/2001/04/witnesses-unto-me?lang=eng"]],
 quiz:[["D&C 4:2 says to serve God with all your…",["heart, might, mind and strength","faith, hope, and charity","time, talents, and means"],0,"\"With all your heart, might, mind and strength\" (D&C 4:2)."],
  ["According to D&C 18:16, how great will your joy be if you bring one soul to Christ?",["Small but real","Great","Unmeasurable only in the next life"],1,"\"How great shall be your joy with him in the kingdom of my Father\" (D&C 18:15–16)."],
  ["1 Peter 3:15 says to be ready always to give what?",["A sermon","An answer for the hope that is in you","A sign"],1,"\"An answer to every man that asketh you a reason of the hope that is in you\" (1 Peter 3:15)."]]},
];
const SKIPS={"Sep 20":"No class; stake conference","Oct 4":"No class; general conference","Oct 18":"No class; both teachers away","Dec 20":"No second hour; Christmas"};
const ORDER=["Sep 6","Sep 13","Sep 20","Sep 27","Oct 4","Oct 11","Oct 18","Oct 25","Nov 1","Nov 8","Nov 15","Nov 22","Nov 29","Dec 6","Dec 13","Dec 20","Dec 27"];
module.exports={GL,SEGMENTS,LESSONS,SKIPS,ORDER};
